blank_issues_enabled: false
contact_links:
  - name: Report a vulnerability
    url: https://github.com/ValkoinenKissa/reservapp-web/security/policy
    about: To report a vulnerability, use GitHub Private Vulnerability Reporting feature.
